name: Validate JSONs

on:
  pull_request:
  push:
    branches:
      - "*"

jobs:
  validate_json:
    name: Validate JSON files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate Alliance Contributions
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: schemas/alliance_contributions.json
          jsons: alliance_contributions/*.json
      - name: Validate Buildings
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: schemas/buildings.json
          jsons: buildings/*.json
      - name: Validate Officers
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: schemas/officers.json
          jsons: officers/*.json
      - name: Validate Refits
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: schemas/refits.json
          jsons: refits/*.json
      - name: Validate Research
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: schemas/research.json
          jsons: research/*.json
      - name: Validate Ships
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: schemas/ships.json
          jsons: ships/*.json
      - name: Validate Systems
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: schemas/systems.json
          jsons: systems/*.json
      - name: Validate Territories
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: schemas/territories.json
          jsons: territories/*.json
      - name: Validate Hostiles
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: schemas/hostiles.json
          jsons: hostiles/*.json
      - name: Validate Dailies
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: schemas/dailies.json
          jsons: dailies/*.json
      - name: Validate Faction Reputation
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: schemas/faction_reputation.json
          jsons: faction_reputation/*.json
      - name: Validate Armadas
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: schemas/armadas.json
          jsons: armadas/*.json
      - name: Validate Missions
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: schemas/missions.json
          jsons: missions/*.json
